//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOtomasyon.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilet
    {
        public int IDBilet { get; set; }
        public int PersonelID { get; set; }
        public int SeferDetayID { get; set; }
        public int MusteriID { get; set; }
        public Nullable<int> PromosyonID { get; set; }
        public int Ucret { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public int KoltukNo { get; set; }
        public Nullable<int> KoltukTipiID { get; set; }
        public Nullable<int> OdemeTipiID { get; set; }
        public int KoltukDurumuID { get; set; }
        public int BinisYeri { get; set; }
        public int InisYeri { get; set; }
        public bool Durum { get; set; }
    
        public virtual KoltukDurumlari KoltukDurumlari { get; set; }
        public virtual KoltukTipleri KoltukTipleri { get; set; }
        public virtual OdemeTipleri OdemeTipleri { get; set; }
        public virtual Promosyonlar Promosyonlar { get; set; }
    }
}
