//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOtomasyon.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Harcamalar
    {
        public int IDHarcama { get; set; }
        public int SeferDetayID { get; set; }
        public int HarcamaTipiID { get; set; }
        public decimal Ucret { get; set; }
        public string Aciklama { get; set; }
    
        public virtual HarcamaTipleri HarcamaTipleri { get; set; }
        public virtual SeferDetay SeferDetay { get; set; }
    }
}
