//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOtomasyon.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otobus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Otobus()
        {
            this.OtobusOzellikDetay = new HashSet<OtobusOzellikDetay>();
            this.SeferDetay = new HashSet<SeferDetay>();
        }
    
        public int IDOtobus { get; set; }
        public int SubeID { get; set; }
        public int OtobusTipiID { get; set; }
        public int OtobusDurumuID { get; set; }
        public int KoltukSayisi { get; set; }
        public string PlakaNo { get; set; }
    
        public virtual OtobusDurumlari OtobusDurumlari { get; set; }
        public virtual OtobusTipleri OtobusTipleri { get; set; }
        public virtual Sube Sube { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtobusOzellikDetay> OtobusOzellikDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeferDetay> SeferDetay { get; set; }
    }
}
