//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOtomasyon.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pnuretSu_otobusEntities : DbContext
    {
        public pnuretSu_otobusEntities()
            : base("name=pnuretSu_otobusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bilet> Bilet { get; set; }
        public virtual DbSet<Guzergahlar> Guzergahlar { get; set; }
        public virtual DbSet<Harcamalar> Harcamalar { get; set; }
        public virtual DbSet<HarcamaTipleri> HarcamaTipleri { get; set; }
        public virtual DbSet<IslemKayitlari> IslemKayitlari { get; set; }
        public virtual DbSet<IslemKayitTipleri> IslemKayitTipleri { get; set; }
        public virtual DbSet<KoltukDurumlari> KoltukDurumlari { get; set; }
        public virtual DbSet<KoltukTipleri> KoltukTipleri { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<MusteriKartlari> MusteriKartlari { get; set; }
        public virtual DbSet<OdemeTipleri> OdemeTipleri { get; set; }
        public virtual DbSet<Otobus> Otobus { get; set; }
        public virtual DbSet<OtobusDurumlari> OtobusDurumlari { get; set; }
        public virtual DbSet<OtobusOzellikDetay> OtobusOzellikDetay { get; set; }
        public virtual DbSet<OtobusOzellikleri> OtobusOzellikleri { get; set; }
        public virtual DbSet<OtobusTipleri> OtobusTipleri { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Promosyonlar> Promosyonlar { get; set; }
        public virtual DbSet<PromosyonTipleri> PromosyonTipleri { get; set; }
        public virtual DbSet<SeferGuzergahi> SeferGuzergahi { get; set; }
        public virtual DbSet<SeferPersonel> SeferPersonel { get; set; }
        public virtual DbSet<SeferTipleri> SeferTipleri { get; set; }
        public virtual DbSet<Sehirler> Sehirler { get; set; }
        public virtual DbSet<Sube> Sube { get; set; }
        public virtual DbSet<Unvanlar> Unvanlar { get; set; }
        public virtual DbSet<Sefer> Sefer { get; set; }
        public virtual DbSet<SeferDetay> SeferDetay { get; set; }
        public virtual DbSet<YetkiTipleri> YetkiTipleri { get; set; }
        public virtual DbSet<Servis> Servis { get; set; }
        public virtual DbSet<Yetki> Yetki { get; set; }
        public virtual DbSet<Formlar> Formlar { get; set; }
        public virtual DbSet<Modul> Modul { get; set; }
        public virtual DbSet<VardiyaKayitlari> VardiyaKayitlari { get; set; }
        public virtual DbSet<Musteri> Musteri { get; set; }
    }
}
