//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOtomasyon.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtobusOzellikDetay
    {
        public int IDOtobusOzellikDetay { get; set; }
        public int OtobusOzellikID { get; set; }
        public int OtobusID { get; set; }
    
        public virtual Otobus Otobus { get; set; }
        public virtual OtobusOzellikleri OtobusOzellikleri { get; set; }
    }
}
