//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOtomasyon.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promosyonlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promosyonlar()
        {
            this.Bilet = new HashSet<Bilet>();
        }
    
        public int IDPromosyon { get; set; }
        public int PromosyonMiktari { get; set; }
        public System.DateTime BaslangicTarihi { get; set; }
        public System.DateTime BitisTarihi { get; set; }
        public Nullable<int> PromosyonTipiID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bilet> Bilet { get; set; }
        public virtual PromosyonTipleri PromosyonTipleri { get; set; }
    }
}
