//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOtomasyon.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeferDetay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeferDetay()
        {
            this.Harcamalar = new HashSet<Harcamalar>();
            this.SeferPersonel = new HashSet<SeferPersonel>();
            this.Servis = new HashSet<Servis>();
        }
    
        public int IDSeferDetay { get; set; }
        public int SeferID { get; set; }
        public Nullable<int> OtobusID { get; set; }
        public Nullable<System.DateTime> SeferTarihi { get; set; }
        public string SeferSaati { get; set; }
        public decimal Ucret { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Harcamalar> Harcamalar { get; set; }
        public virtual Otobus Otobus { get; set; }
        public virtual Sefer Sefer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeferPersonel> SeferPersonel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servis> Servis { get; set; }
    }
}
