//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOtomasyon.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servis
    {
        public int IDServis { get; set; }
        public int SeferDetayID { get; set; }
        public string KalkisYeri { get; set; }
        public string KalkisSaati { get; set; }
        public Nullable<int> OtobusID { get; set; }
        public Nullable<decimal> ServisUcreti { get; set; }
    
        public virtual SeferDetay SeferDetay { get; set; }
    }
}
